(()=>{const d=window.portfolioDiagnostics,g=(s,f)=>d?d.guard(s,f):f,k='portfolio:tab-started-at',now=Date.now(),FIVE=300000,prev=Number.parseInt(sessionStorage.getItem(k)||'0',10),original=!prev||now-prev>=FIVE;if(original)sessionStorage.setItem(k,String(now));
const load=s=>new Promise((r,j)=>{const x=document.createElement('script');x.src=s;x.async=false;x.onload=r;x.onerror=()=>j(Error(`Failed to load ${s}`));document.head.appendChild(x)});
const loadStyle=(href,media='')=>new Promise((r,j)=>{if(document.querySelector(`link[href^="${href.split('?')[0]}"]`)){r();return}const l=document.createElement('link');l.rel='stylesheet';l.href=href;if(media)l.media=media;l.onload=r;l.onerror=()=>j(Error(`Failed to load ${href}`));document.head.appendChild(l)});
loadStyle('./mobile-responsive.css?v=2','(max-width: 760px)').catch(e=>console.warn('Mobile layout engine:',e));
const showPoster=()=>{if(document.getElementById('galaxy-dynamic-bg'))return;const legacy=document.getElementById('molecule-bg');if(legacy)legacy.remove();const p=document.createElement('div');p.id='galaxy-dynamic-bg';p.setAttribute('aria-hidden','true');p.style.cssText='position:fixed;inset:0;width:100vw;height:100dvh;z-index:0;pointer-events:none;overflow:hidden;background:radial-gradient(circle at 68% 42%,rgba(103,232,249,.10),transparent 34%),radial-gradient(circle at 35% 65%,rgba(167,139,250,.08),transparent 40%),var(--theme-bg,#05070A)';document.body.prepend(p)};
if(!original){showPoster();const theme=load('./theme.js?v=15').catch(e=>{console.warn('Theme engine:',e);throw e});load('./font-curator.js?v=7').catch(e=>console.warn('Font engine:',e));theme.then(()=>loadStyle('./theme-panels.css?v=1')).catch(e=>console.warn('Theme panel engine:',e));load('./vendor/galaxy.min.js?v=3.4.0').then(()=>load('./galaxy-background.js?v=5')).catch(e=>console.warn('GalaxyJS background engine:',e))}
const V=[['home','#home','home-active','.hero'],['about','#about','about-active','.about-panel'],['experience','#experience','experience-active','.experience-panel'],['arsenal','#arsenal','arsenal-active','.arsenal-rebuild'],['education','#education','education-active','#education'],['publications','#publications','publication-active','#publications'],['beyond','#beyond','beyond-active','#beyond'],['connect','#connect','connect-active','#connect-panel']];
const ready=f=>document.readyState==='loading'?document.addEventListener('DOMContentLoaded',f,{once:true}):f();
function magic(){ready(()=>{const nav=document.querySelector('.sidebar nav');if(!nav||nav.querySelector('[data-magic-reload="true"]'))return;const a=document.createElement('a');a.href='#magic';a.dataset.magicReload='true';a.setAttribute('aria-label','Open the Multiverse');a.title='Open the Multiverse';a.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="3"></circle><ellipse cx="12" cy="12" rx="9" ry="4.2" transform="rotate(-25 12 12)"></ellipse><ellipse cx="12" cy="12" rx="9" ry="4.2" transform="rotate(25 12 12)"></ellipse><circle cx="18.9" cy="7.2" r="1.15" fill="currentColor" stroke="none"></circle></svg><span>OPEN THE MULTIVERSE</span>';a.addEventListener('click',g('magic reload',e=>{e.preventDefault();sessionStorage.setItem(k,String(Date.now()));location.reload()}));nav.appendChild(a)})}magic();
function loadAbout(){if(document.getElementById('about-responsive-fix'))return;const l=document.createElement('link');l.id='about-responsive-fix';l.rel='stylesheet';l.href='./about-responsive-fix.css?v=2';document.head.appendChild(l)}
function inject(id,css){document.getElementById(id)?.remove();const s=document.createElement('style');s.id=id;s.textContent=css;document.head.appendChild(s);const pp=document.getElementById('professional-polish');if(pp)document.head.appendChild(pp);loadAbout();return s}
function renderPanel({id,className,html,styleId,css,parent='.content',scope=id}){const c=document.querySelector(parent);if(!c){d?.reportMissing(scope,`${parent} container`);return null}document.getElementById(id)?.remove();document.getElementById(styleId)?.remove();const s=document.createElement('section');s.id=id;s.className=className;s.innerHTML=html;c.appendChild(s);inject(styleId,css);return s}
function removePanel(id,styleId){document.getElementById(id)?.remove();document.getElementById(styleId)?.remove()}
function setNav(hash){document.querySelectorAll('.sidebar nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')===hash))}
function activate(hash){const x=V.find(v=>v[1]===hash);if(!x)return;V.forEach(v=>document.body.classList.remove(v[2]));document.body.classList.add(x[2]);setNav(hash)}
function bindPanelRoute({hash,show,hide,scope=hash}){ready(()=>{const l=document.querySelector(`.sidebar nav a[href="${hash}"]`);if(!l){d?.reportMissing(scope,`the ${hash} sidebar link`);return}l.addEventListener('click',g(scope,e=>{e.preventDefault();show()}));window.addEventListener('hashchange',g(scope,()=>location.hash===hash?show():hide()));if(location.hash===hash)g(scope,show)()})}
function gradientText(x){return`background:${x};-webkit-background-clip:text;background-clip:text;color:transparent;`}
function panelCss(){return V.map(([, ,bc,sel])=>{const h=V.filter(v=>v[2]!==bc).map(v=>`body.${bc} ${v[3]}`).join(',');return`${h}{display:none!important}`}).join('')}
inject('panel-visibility-style',panelCss());
window.Portfolio={VIEWS:V.map(([view,hash,bodyClass,selector])=>({view,hash,bodyClass,selector})),renderPanel,removePanel,activateView:activate,bindPanelRoute,gradientText};
})();